Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 71, in auth_register
    raise InputError(description='Invalid email')
error.InputError: 400 Bad Request: Invalid email
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 75, in auth_register
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 75, in auth_register
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 77, in auth_register
    raise InputError(description='Invalid first name or last name')
error.InputError: 400 Bad Request: Invalid first name or last name
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 77, in auth_register
    raise InputError(description='Invalid first name or last name')
error.InputError: 400 Bad Request: Invalid first name or last name
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 77, in auth_register
    raise InputError(description='Invalid first name or last name')
error.InputError: 400 Bad Request: Invalid first name or last name
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 77, in auth_register
    raise InputError(description='Invalid first name or last name')
error.InputError: 400 Bad Request: Invalid first name or last name
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 73, in auth_register
    raise InputError(description='Email already in use')
error.InputError: 400 Bad Request: Email already in use
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 89, in svr_auth_register
    email = req['email']
KeyError: 'email'
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 89, in svr_auth_register
    email = req['email']
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 23, in auth_login
    raise InputError(description='Email not registered')
error.InputError: 400 Bad Request: Email not registered
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 25, in auth_login
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 21, in auth_login
    raise InputError(description='Invalid email')
error.InputError: 400 Bad Request: Invalid email
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 21, in auth_login
    raise InputError(description='Invalid email')
error.InputError: 400 Bad Request: Invalid email
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 25, in auth_login
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 81, in svr_auth_login
    email = req['email']
KeyError: 'email'
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 81, in svr_auth_login
    email = req['email']
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 71, in auth_register
    raise InputError(description='Invalid email')
error.InputError: 400 Bad Request: Invalid email
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 75, in auth_register
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 75, in auth_register
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 77, in auth_register
    raise InputError(description='Invalid first name or last name')
error.InputError: 400 Bad Request: Invalid first name or last name
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 77, in auth_register
    raise InputError(description='Invalid first name or last name')
error.InputError: 400 Bad Request: Invalid first name or last name
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 77, in auth_register
    raise InputError(description='Invalid first name or last name')
error.InputError: 400 Bad Request: Invalid first name or last name
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 77, in auth_register
    raise InputError(description='Invalid first name or last name')
error.InputError: 400 Bad Request: Invalid first name or last name
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 73, in auth_register
    raise InputError(description='Email already in use')
error.InputError: 400 Bad Request: Email already in use
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 89, in svr_auth_register
    email = req['email']
KeyError: 'email'
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 89, in svr_auth_register
    email = req['email']
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 23, in auth_login
    raise InputError(description='Email not registered')
error.InputError: 400 Bad Request: Email not registered
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 25, in auth_login
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 21, in auth_login
    raise InputError(description='Invalid email')
error.InputError: 400 Bad Request: Invalid email
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 21, in auth_login
    raise InputError(description='Invalid email')
error.InputError: 400 Bad Request: Invalid email
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 25, in auth_login
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 81, in svr_auth_login
    email = req['email']
KeyError: 'email'
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 81, in svr_auth_login
    email = req['email']
TypeError: list indices must be integers or slices, not str
